secrets:
  postgres_password:
    file: ./secrets/postgres_pass.txt
  pgadmin_password:
    file: ./secrets/pgadmin_pass.txt

services:
  postgres:
    image: postgres
    secrets:
      - postgres_password
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresql/data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    secrets:
      - pgadmin_password
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD_FILE=/run/secrets/pgadmin_password
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
    volumes:
      - ./data/pgadmin/data:/var/lib/pgadmin/data
      - ./data/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

# volumes:
#   fastapi-app-data:
#   fastapi-app-pgadmin-preference:
